; Configuración del entorno PlatformIO para CLion
; Microcontrolador: ATmega2560 (Proteus)
; Framework: Arduino (Permite usar el archivo .ino)

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Opcional: Si en algún momento vas a conectar una placa física al PC,
; PlatformIO suele detectar el puerto COM solo, pero si Proteus lo requiere
; o quieres forzar la velocidad del monitor serial, puedes descomentar esto:
; monitor_speed = 9600